name: Run Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run Docker Container
      run: docker run --rm dmitrykiteam/webdriverio-tests
